// All UI text lives here so a German version can be added later.
export const strings = {
  appName: 'OurLife',
  dayTitle: (n: number) => `Day ${n}`,
  together: (date: string) => `together since ${date}`,
  dotLabel: (n: number, date: string) => `Day ${n}, ${date}`,
  addText: 'Text',
  addSticker: 'Sticker',
  addTape: 'Tape',
  addPhoto: 'Photo',
  goalsTitle: 'Goals',
  settingsTitle: 'Settings',
  settingsColorTitle: 'Your colour',
  settingsColorHint: 'New text, to-dos and tape start in this colour on this phone.',
  settingsStartTitle: 'Our start date',
  settingsStartHint: 'Day 1 of your grid. Both phones should use the same date.',
  settingsStartSave: 'Save date',
  settingsStartSaved: 'Saved.',
  settingsStartInvalid: 'Write a date in the past like 2025-10-12.',
  goalsEmpty: 'No goals yet. Create one below, then write /goal name +50 on any day.',
  newGoalTitle: 'New goal',
  goalNamePlaceholder: 'Name, e.g. Car',
  goalTargetPlaceholder: 'Target, e.g. 10000',
  goalUnitPlaceholder: 'Unit, e.g. EUR',
  goalDeadlinePlaceholder: 'Deadline (optional) YYYY-MM-DD',
  goalCreate: 'Create goal',
  goalNeedsName: 'Give your goal a name.',
  goalNameTaken: 'You already have a goal with that name.',
  goalNeedsTarget: 'The target must be a number above 0.',
  goalBadDeadline: 'Write the deadline like 2026-12-31.',
  goalTotal: (total: string, target: string) => `${total} of ${target}`,
  goalDeadline: (date: string) => `by ${date}`,
  goalEntriesTitle: 'Entries',
  goalNoEntries: 'Nothing added yet. Write /goal name +50 on a day page.',
  goalDelete: 'Delete goal',
  goalNotFound: 'This goal no longer exists.',
  goalSuggestionLabel: (name: string) => `Use goal ${name}`,
  goalChip: (name: string) => name,
  addTodo: 'To-do',
  addFocus: 'Focus',
  addMood: 'Mood',
  todoTitle: 'To do',
  focusTitle: 'Focus',
  todoPlaceholder: 'One task per line',
  focusPlaceholder: 'What matters most today?',
  moodSheetTitle: 'How was today?',
  taskLabel: (text: string, done: boolean) => `${text}, ${done ? 'done' : 'not done'}`,
  photoLabel: 'Photo',
  photoNotShared: 'The photo is on this phone only. Could not share it with your partner.',
  photoFailed: 'Could not add that photo. Try another one.',
  textPlaceholder: 'Write something… or /goal car +50',
  textSave: 'Save',
  textCancel: 'Cancel',
  stickerSheetTitle: 'Pick a sticker',
  close: 'Close',
  delete: 'Delete',
  toFront: 'Bring to front',
  pairTitle: 'Our space',
  pairIntro: 'One shared place for your days. Two phones, one code.',
  pairCreateTitle: 'Start our space',
  pairCreateHint: (date: string) => `Choose this if you are the first one. Day 1 will be ${date}. You get a code for your partner.`,
  pairCreateButton: 'Create our space',
  pairJoinTitle: 'I have a code',
  pairJoinHint: 'Paste the code your partner sent you. Pages already on this phone are replaced by your shared space.',
  pairJoinPlaceholder: 'Paste the code',
  pairJoinButton: 'Join',
  pairBusy: 'One moment…',
  pairRetry: 'Try again',
  pairCreatedTitle: 'Your space is ready',
  pairCreatedHint: 'Send this code to your partner. It is the only key: whoever has it can join, and only two people fit.',
  pairContinue: 'Continue',
  settingsSpaceTitle: 'Pairing code',
  settingsSpaceHint: 'Keep it private. It is only needed once, on your partner’s phone.',
  colorLabel: (name: string) => `Colour ${name}`,
} as const;
