// All UI text lives here so a German version can be added later.
export const strings = {
  appName: 'OurLife',
  dayTitle: (n: number) => `Day ${n}`,
  together: (date: string) => `together since ${date}`,
  dotLabel: (n: number, date: string) => `Day ${n}, ${date}`,
  addText: 'Text',
  addSticker: 'Sticker',
  addTape: 'Tape',
  addPhoto: 'Photo',
  goalsTitle: 'Goals',
  settingsTitle: 'Settings',
  settingsColorTitle: 'Your colour',
  settingsColorHint: 'New text, to-dos and tape start in this colour on this phone.',
  settingsStartTitle: 'Our start date',
  settingsStartHint: 'Day 1 of your grid. Both phones should use the same date.',
  settingsStartSave: 'Save date',
  settingsStartSaved: 'Saved.',
  settingsStartInvalid: 'Write a date in the past like 2025-10-12.',
  goalsEmpty: 'No goals yet. Create one below, then write /goal name +50 on any day.',
  newGoalTitle: 'New goal',
  goalNamePlaceholder: 'Name, e.g. Car',
  goalTargetPlaceholder: 'Target, e.g. 10000',
  goalUnitPlaceholder: 'Unit, e.g. EUR',
  goalDeadlinePlaceholder: 'Deadline (optional) YYYY-MM-DD',
  goalCreate: 'Create goal',
  goalNeedsName: 'Give your goal a name.',
  goalNameTaken: 'You already have a goal with that name.',
  goalNeedsTarget: 'The target must be a number above 0.',
  goalBadDeadline: 'Write the deadline like 2026-12-31.',
  goalTotal: (total: string, target: string) => `${total} of ${target}`,
  goalDeadline: (date: string) => `by ${date}`,
  goalEntriesTitle: 'Entries',
  goalNoEntries: 'Nothing added yet. Write /goal name +50 on a day page.',
  goalDelete: 'Delete goal',
  goalNotFound: 'This goal no longer exists.',
  goalSuggestionLabel: (name: string) => `Use goal ${name}`,
  goalChip: (name: string) => name,
  addTodo: 'To-do',
  addFocus: 'Focus',
  addMood: 'Mood',
  todoTitle: 'To do',
  focusTitle: 'Focus',
  todoPlaceholder: 'One task per line',
  focusPlaceholder: 'What matters most today?',
  moodSheetTitle: 'How was today?',
  taskLabel: (text: string, done: boolean) => `${text}, ${done ? 'done' : 'not done'}`,
  photoLabel: 'Photo',
  photoNotShared: 'The photo is on this phone only. Could not share it with your partner.',
  photoFailed: 'Could not add that photo. Try another one.',
  textPlaceholder: 'Write something… or /goal car +50',
  textSave: 'Save',
  textCancel: 'Cancel',
  stickerSheetTitle: 'Pick a sticker',
  stickerLabel: 'Sticker',
  libraryTabEmoji: 'Emoji',
  libraryTabStickers: 'Stickers',
  libraryTabGifs: 'GIFs',
  librarySearchPlaceholder: 'Search KLIPY',
  libraryPowered: 'Powered by KLIPY',
  libraryLoadFailed: 'Could not load the library. Check your internet and try again.',
  libraryEmpty: 'Nothing found. Try another word.',
  libraryUseLabel: (title: string) => `Use ${title || 'this one'}`,
  close: 'Close',
  delete: 'Delete',
  toFront: 'Bring to front',
  pairTitle: 'Our space',
  pairIntro: 'One shared place for your days. Everyone in the space shares one code.',
  pairCreateTitle: 'Start our space',
  pairCreateHint: 'Choose this if you are the first one. You set it up and get a code for the others.',
  pairCreateButton: 'Set up our space',
  pairJoinTitle: 'I have a code',
  pairJoinHint: 'Paste the code you were sent. Pages already on this phone are replaced by the shared space.',
  pairJoinPlaceholder: 'Paste the code',
  pairJoinButton: 'Join',
  pairBusy: 'One moment…',
  pairRetry: 'Try again',
  pairCreatedTitle: 'Your space is ready',
  pairCreatedHint: 'Send this code to the people who should join. It is the only key: whoever has it can join. You can make a new code in Settings at any time.',
  pairContinue: 'Continue',
  setupTitle: 'Set up our space',
  setupSpaceName: 'Name of the space',
  setupSpaceNamePlaceholder: 'e.g. Momo & Bibble',
  setupYourName: 'Your name',
  setupYourNameHint: 'So the others can tell your phone from theirs.',
  setupStartDate: 'Start date (Day 1)',
  setupStartDateInvalid: 'Write a date in the past like 2025-10-12.',
  setupGoalsTitle: 'Goals (optional)',
  setupGoalsHint: 'You can always add more later.',
  setupGoalAdded: (name: string) => `Remove goal ${name}`,
  setupNeedsSpaceName: 'Give your space a name.',
  setupNeedsYourName: 'Write your name.',
  setupBack: 'Back',
  joinYourName: 'Your name',
  joinNeedsName: 'Write your name first.',
  settingsSpaceTitle: 'Space',
  settingsSpaceNameTitle: 'Name of the space',
  settingsSpaceNameSave: 'Save name',
  settingsCodeTitle: 'Pairing code',
  settingsCodeHint: 'Whoever has this code can join the space. Keep it private.',
  settingsCodeNew: 'Make a new code',
  settingsCodeNewHint: 'The old code stops working. People already in the space stay.',
  settingsMembersTitle: 'People in this space',
  settingsMembersHint: 'Everyone here can add or remove people. Lost a phone? Join from the new one with the code, then remove the old entry here.',
  settingsMemberYou: 'this phone',
  settingsMemberUnnamed: 'Unnamed phone',
  settingsMemberRename: 'Your name',
  settingsMemberRenameSave: 'Save my name',
  settingsMemberRemove: 'Remove',
  settingsMemberRemoveLabel: (name: string) => `Remove ${name} from this space`,
  settingsMemberRemoveConfirm: 'Tap again to remove',
  settingsMembersFailed: 'Could not load the people. Check your internet.',
  colorLabel: (name: string) => `Colour ${name}`,
} as const;
