// All UI text lives here so a German version can be added later.
export const strings = {
  appName: 'OurLife',
  dayTitle: (n: number) => `Day ${n}`,
  together: (date: string) => `together since ${date}`,
  dotLabel: (n: number, date: string) => `Day ${n}, ${date}`,
  addText: 'Text',
  addSticker: 'Sticker',
  addTape: 'Tape',
  addPhoto: 'Photo',
  addTodo: 'To-do',
  addFocus: 'Focus',
  addMood: 'Mood',
  todoTitle: 'To do',
  focusTitle: 'Focus',
  todoPlaceholder: 'One task per line',
  focusPlaceholder: 'What matters most today?',
  moodSheetTitle: 'How was today?',
  taskLabel: (text: string, done: boolean) => `${text}, ${done ? 'done' : 'not done'}`,
  photoLabel: 'Photo',
  photoFailed: 'Could not add that photo. Try another one.',
  textPlaceholder: 'Write something…',
  textSave: 'Save',
  textCancel: 'Cancel',
  stickerSheetTitle: 'Pick a sticker',
  close: 'Close',
  delete: 'Delete',
  toFront: 'Bring to front',
  colorLabel: (name: string) => `Colour ${name}`,
} as const;
